#!/bin/bash

#PBS -l nodes=30:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N NeuroNet
#PBS -M sahandha@gmail.com
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
#PBS -l flags=commlocal:commtolerant

cd $PBS_O_WORKDIR
module load bwpy
module load bwpy-mpi

aprun -n 960 -N 32 python3 -m cProfile -o /u/eot/hariria2/scratch/Parallel/Sim5_06262017/program.prof.bw ./run.py -N 96000 -S 5 -L 500 -D 10 -P 200 -O /u/eot/hariria2/scratch/Parallel/Sim5_06262017
