#!/bin/bash


#PBS -l nodes=5:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N NeuroNet
#PBS -M sahandha@gmail.com
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
#PBS -l flags=commlocal:commtolerant

cd $PBS_O_WORKDIR
module load bwpy
module load bwpy-mpi

aprun -n 80 -N 16 python3 -m cProfile -o /u/eot/hariria2/scratch/Parallel/Sim0_06232017/program.prof.bw ./run.py -N 8000 -S 10 -L 1000 -D 1000 -P 200 -O /u/eot/hariria2/scratch/Parallel/Sim2_06232017
